### ISSUE TITLE
Allow resubmitting cancelled/unsuccessful jobs

### ISSUE THREAD

**Issue by zerolab** [mozilla/wagtail-localize-smartling#26]
We could use the same message banner on the page edit view that currently displays the "This translation is managed by Smartling" message but, when the latest translation job for the page is cancelled/deleted show a message to indicate that and include a button to press that will submit the job again: "The latest Smartling job for this translation was {cancelled/deleted}. [Resubmit to Smartling]"

**Comment by stevejalim** [comment]
That sounds good to me. Thanks!
