### ISSUE TITLE
String concatenation problems with strings pulled back from Smartling

### ISSUE THREAD

**Issue by stevejalim** [mozilla/wagtail-localize-smartling#31]
When paragraphs of text are entered into a RichTextField and ultimately sent to Smartling, they are split into sentences.

These are translated at the Smarlting end and, when complete, flow back to Wagtail.

However, in Wagtail, the reconstituted paragraphs are missing spaces between individual sentences. It may not be every time (or the ones which do not lack spaces actually have trailing spaces in their content.

Edit mode in Smartling
![Screenshot 2024-10-17 at 17 12 42](https://github.com/user-attachments/assets/63ae565d-35ec-4e46-8e24-464a1de753f1)

Completed translation of a paragraph in Smartling
![Screenshot 2024-10-17 at 17 12 37](https://github.com/user-attachments/assets/88af1ae8-4106-4306-8910-59d791ec1cb8)

Resulting richtext flowed back to Wagtail
![Screenshot 2024-10-17 at 17 11 47](https://github.com/user-attachments/assets/f721e34d-085b-4780-9ad7-1671bf79cbaa)

It would make sense to normalise to a single space between strings being concatenated back into a paragraph.

**Comment by stevejalim** [comment]
AFAICT the most obvious touchpoint where this could be happening is actually in wagtail-localize's `Translation.import_po`, but I'd be surprised if all PO files were treated this way. Maybe there's something special about the ones that come out of Smartling, or it's something about how a PO file is cut up when it reaches Smartling...

**Comment by stevejalim** [comment]
OK, looking at this with fresh eyes I can also see examples where the space is missing in Smartling, too – so it's not necessarily a `wagtail-localize`-side thing, which also fits with the code diving I did last night.

![Screenshot 2024-10-18 at 09 20 12](https://github.com/user-attachments/assets/5489b14b-26a3-4955-9b9c-a035e7a7322f)

Rubber-ducking this here, as I've got no one to bounce this off right now, but I wonder if this might be what's happening:

* A long source string from the .po file is broken up in Smartling into smaller strings (sentences)
* Theory: The source-language sentences extracted contain trailing spaces
* The sentences are translated, but don't have trailing spaces
* Smartling reconstitutes the long sring from the sentences, without putting spaces between them (maybe - wild guess - because putting spaces is kind of assumptive about the syntax of the target language)

This may be a dead-end, but worth confirming.

Next step: I guess ideally i need to get hold of the PO file in question.

**Comment by zerolab** [comment]
@stevejalim I think it is worth checking the PO file. You should be able to download it through the Smartling interface, or from the translation edit interface in Wagtail.

If it is a translation process issue (strings get translated and trailing spaces are stripped), we may want to look at the tweaking the [import step[(https://github.com/wagtail/wagtail-localize/blob/caf14b8e276a735f7536d3468762797af5c25315/wagtail_localize/models.py#L1232), which may its own can of worms 🙈

**Comment by stevejalim** [comment]
I've got hold of the source and translated PO files and can see that the lack of spacing is coming in on the Smartling side, not the Wagtail side

Source excerpt
```
msgctxt "title"
msgid "Do you need a VPN at home? Here are 5 reasons you might."
msgstr ""
```

Translation excerpt
```
msgctxt "title"
msgid "Do you need a VPN at home? Here are 5 reasons you might."
msgstr "Avez-vous besoin d’un VPN chez vous ?Voici 5 raisons qui pourraient vous convaincre que oui."
```

**Comment by stevejalim** [comment]
@zerolab Thanks for the comment! It looks like this isn't `wagtail-localize` doing anything wrong, and it's on the translation side.

My concern is that it's not going to be pragmatic to ensure that human translators always remember to match whether or not a source string has a trailing space, but I'm discussing that angle with colleagues here.

If we can't guarantee that trailing spaces will be respected, I'm wondering whether there's a solution based on chunking down further at the PO generation stage (ideally via w-l-smartling, not w-l) so that we only sent strings that are at most a sentence, but that may not be practical

**Comment by stevejalim** [comment]
I'll take a look at https://github.com/wagtail/wagtail-localize/blob/caf14b8e276a735f7536d3468762797af5c25315/wagtail_localize/models.py#L1232 and get my can-opener ready 😬

**Comment by stevejalim** [comment]
Closing in favour of https://github.com/mozilla/wagtail-localize-smartling/issues/34
